# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

sources = ['git@github.com:CocoaPods/Specs']
podspec = './Stringify.podspec'
xcodeproj = 'Stringify.xcodeproj'
target = 'Stringify'

lane :release do
	pod_lib_lint(
		podspec: podspec,
		allow_warnings: true
	)

	build_version = get_version_number(
		xcodeproj: xcodeproj,
		target: target
	)

	version_bump_podspec(
		path: podspec,
		version_number: build_version
	)

	git_commit(
		path: podspec,
		message: "Update #{podspec}",
		allow_nothing_to_commit: true
	)

	sh("git tag '#{build_version}'")
	sh("git push --tags")

	pod_push(
		path: podspec,
		verbose: true,
		allow_warnings: true
	)
end
